/**
 * @fileoverview gRPC-Web generated client stub for todolist
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: todolist.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as todolist_pb from './todolist_pb';


export class TodoListClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetItems = new grpcWeb.MethodDescriptor(
    '/todolist.TodoList/GetItems',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    todolist_pb.GetItemsResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    todolist_pb.GetItemsResponse.deserializeBinary
  );

  getItems(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<todolist_pb.GetItemsResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/todolist.TodoList/GetItems',
      request,
      metadata || {},
      this.methodDescriptorGetItems);
  }

  methodDescriptorPostItem = new grpcWeb.MethodDescriptor(
    '/todolist.TodoList/PostItem',
    grpcWeb.MethodType.UNARY,
    todolist_pb.PostItemRequest,
    todolist_pb.PostItemResponse,
    (request: todolist_pb.PostItemRequest) => {
      return request.serializeBinary();
    },
    todolist_pb.PostItemResponse.deserializeBinary
  );

  postItem(
    request: todolist_pb.PostItemRequest,
    metadata: grpcWeb.Metadata | null): Promise<todolist_pb.PostItemResponse>;

  postItem(
    request: todolist_pb.PostItemRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: todolist_pb.PostItemResponse) => void): grpcWeb.ClientReadableStream<todolist_pb.PostItemResponse>;

  postItem(
    request: todolist_pb.PostItemRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: todolist_pb.PostItemResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/todolist.TodoList/PostItem',
        request,
        metadata || {},
        this.methodDescriptorPostItem,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/todolist.TodoList/PostItem',
    request,
    metadata || {},
    this.methodDescriptorPostItem);
  }

}

